nats-streaming image should be created with a non-root user (#116)
* nats-streaming: image should be created with a non root user

* bump alpine to 3.14

* Fix version

Co-authored-by: Daniel Hoherd <daniel.hoherd@gmail.com>

diff --git a/nats-streaming/Dockerfile b/nats-streaming/Dockerfile
--- a/nats-streaming/Dockerfile
+++ b/nats-streaming/Dockerfile
@@ -13,11 +13,47 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-# https://hub.docker.com/_/nats-streaming
-FROM nats-streaming:0.21.2-alpine3.13
+FROM alpine:3.14
 
 LABEL maintainer="Astronomer <humans@astronomer.io>"
 
 ARG BUILD_NUMBER=-1
 LABEL io.astronomer.docker=true
 LABEL io.astronomer.docker.build.number=$BUILD_NUMBER
+
+
+ENV NATS_STREAMING_SERVER 0.22.0
+
+# Create nats-streamming user and group
+RUN addgroup -g 1000 -S nats-streaming \
+    && adduser -u 1000 -S nats-streaming -G nats-streaming
+
+RUN set -eux; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		aarch64) natsArch='arm64'; sha256='3ffc4b74f469b97a8ce0edff8b645baf89d9f9f3debdfa7088a0ceac3ed6c37b' ;; \
+		armhf) natsArch='arm6'; sha256='abe201b1a90cd2e8db39989c81a2c76d3956035745c68d0c7e090fc8c5a138c8' ;; \
+		armv7) natsArch='arm7'; sha256='d218edd395f980ea91a54624b4cc1fe0220268171ee596a24d7c01c15a7dbb7f' ;; \
+		x86_64) natsArch='amd64'; sha256='72f5b899167a8866d4b82d1bf9bc14b5d047e6b1ab127dd0085e9eb91a89f097' ;; \
+		x86) natsArch='386'; sha256='d87bb204228c5e820747e1682dbfb56289e3ddadcfe129b9c9fcf1ad7c0ba053' ;; \
+		*) echo >&2 "error: $apkArch is not supported!"; exit 1 ;; \
+	esac; \
+	\
+	wget -O nats-streaming-server.zip "https://github.com/nats-io/nats-streaming-server/releases/download/v${NATS_STREAMING_SERVER}/nats-streaming-server-v${NATS_STREAMING_SERVER}-linux-${natsArch}.zip"; \
+	echo "${sha256} *nats-streaming-server.zip" | sha256sum -c -; \
+	\
+	apk add --no-cache ca-certificates; \
+	apk add --no-cache --virtual buildtmp unzip; \
+	\
+	unzip nats-streaming-server.zip "nats-streaming-server-v${NATS_STREAMING_SERVER}-linux-${natsArch}/nats-streaming-server"; \
+	rm nats-streaming-server.zip; \
+	mv "nats-streaming-server-v${NATS_STREAMING_SERVER}-linux-${natsArch}/nats-streaming-server" /usr/local/bin; \
+	rmdir "nats-streaming-server-v${NATS_STREAMING_SERVER}-linux-${natsArch}"; \
+	\
+	apk del --no-cache --no-network buildtmp
+
+COPY --chown=1000:1000 docker-entrypoint.sh /usr/local/bin
+EXPOSE 4222 8222
+USER nats-streaming
+ENTRYPOINT ["docker-entrypoint.sh"]
+CMD ["nats-streaming-server", "-m", "8222"]
