nats image should be created with a non-root user (#117)
* nats: image should be created with a non root user

* Fix version

Co-authored-by: Daniel Hoherd <daniel.hoherd@gmail.com>

diff --git a/nats-server/Dockerfile b/nats-server/Dockerfile
--- a/nats-server/Dockerfile
+++ b/nats-server/Dockerfile
@@ -13,10 +13,46 @@
 # See the License for the specific language governing permissions and
 # limitations under the License.
 
-FROM nats:2.2.1-alpine3.13
+FROM alpine:3.14
 
 LABEL maintainer="Astronomer <humans@astronomer.io>"
 
 ARG BUILD_NUMBER=-1
 LABEL io.astronomer.docker=true
 LABEL io.astronomer.docker.build.number=$BUILD_NUMBER
+
+ENV NATS_SERVER 2.3.2
+
+# Create nats-streamming user and group
+RUN addgroup -g 1000 -S nats \
+    && adduser -u 1000 -S nats-G nats
+
+RUN set -eux; \
+	apkArch="$(apk --print-arch)"; \
+	case "$apkArch" in \
+		aarch64) natsArch='arm64'; sha256='18a68cbef5c7a41052f5281bdfe9164b51cbeb60ce2dd31a7945c5adbcd39c2d' ;; \
+		armhf) natsArch='arm6'; sha256='a37949f8a1e24d5a8e47f57786e126205de7c3f6f8b3e5b849f33adbcfe8d2fb' ;; \
+		armv7) natsArch='arm7'; sha256='43a4820a57161b83fe721b81098d2ba9b1e2f42923be898f031bac40279f8f6e' ;; \
+		x86_64) natsArch='amd64'; sha256='6e6fdf781465fbf09cb024112b34ae6b2b432d94a5fc8b62f6ebf0da5fc3345d' ;; \
+		x86) natsArch='386'; sha256='c7c0ea9a5343925f0f5e2dda964946152382b0a3e0db96aa43c3f2ab17a37bf0' ;; \
+		*) echo >&2 "error: $apkArch is not supported!"; exit 1 ;; \
+	esac; \
+	\
+	wget -O nats-server.tar.gz "https://github.com/nats-io/nats-server/releases/download/v${NATS_SERVER}/nats-server-v${NATS_SERVER}-linux-${natsArch}.tar.gz"; \
+	echo "${sha256} *nats-server.tar.gz" | sha256sum -c -; \
+	\
+	apk add --no-cache ca-certificates; \
+	apk add --no-cache --virtual buildtmp; \
+	\
+	tar -xf nats-server.tar.gz; \
+	rm nats-server.tar.gz; \
+	mv "nats-server-v${NATS_SERVER}-linux-${natsArch}/nats-server" /usr/local/bin; \
+	rm -rf "nats-server-v${NATS_SERVER}-linux-${natsArch}"; \
+	\
+	apk del --no-cache --no-network buildtmp
+
+COPY --chown=1000:1000 nats-server.conf /etc/nats/nats-server.conf
+COPY --chown=1000:1000 docker-entrypoint.sh /usr/local/bin
+EXPOSE 4222 8222 6222
+ENTRYPOINT ["docker-entrypoint.sh"]
+CMD ["nats-server", "--config", "/etc/nats/nats-server.conf"]
